### ISSUE TITLE
Stop draggability of image.

### ISSUE THREAD

**Issue by imjosecampos-zz** [dennis-learningpool/adapt-slidingPuzzle#2]
Most users are lazy and generally know what to do with a sliding puzzle which is, as the name says, to slide which right now causes the whole image to be dragged which looks bad, this can be fixed by adding:

<code>img.attr('draggable', 'false');</code>

After line 53 of adapt-slidingPuzzle.js

**Comment by imjosecampos-zz** [comment]
Also to improve the sliding part of this component the call to attemptMove can be changed to mouse down by changing line 103 to:

<code>'mousedown .slidingPuzzle-puzzle': 'attemptMove',</code>

**Comment by dennis-learningpool** [comment]
Hi @jscampos - thanks for the suggestions! If you submit these changes as a pull request, I'll happily review and merge.

**Comment by imjosecampos-zz** [comment]
Done.
